name: docker-release-build-and-push

on:
  pull_request:
  workflow_dispatch:
env:
  REGISTRY_IMAGE: rqlite/rqlite

jobs:
  build:
    runs-on: blacksmith-16vcpu-ubuntu-2204-arm
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/arm64
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}

      - name: Build
        id: build
        uses: useblacksmith/build-push-action@v1
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image
          context: .
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
            COMMIT=${{ github.sha }}
            BRANCH=master
            DATE=${{ github.event.created_at }}

  cloud-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "blacksmithcihello/blacksmith-builder"
      
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.REGISTRY_IMAGE }}
          outputs: type=image
